version: '2'
services:
  test:
    image: node:latest
    working_dir: /app
    links:
      - redis
    volumes:
      - .:/app
    environment:
      - NODE_ENV=test
      - REDIS_GENERAL_OVERRIDE_HOST=redis
    command: >
      /bin/sh -c "
        export REDIS_GENERAL_OVERRIDE_PORT=$$REDIS_PORT_6379_TCP_PORT;
        npm install
        npm i -g mocha
        mocha test
      "

  redis:
    image: redis
